# Minicurso Introdução à programação em **Python 3**
## Com ênfase em aplicações numéricas
### Instrutor: João Eduardo Levandoski - Acadêmico de Engenharia Química
### Bolsista CNPq - Brazilian synchrotron light source (LNLS) - IMBUIA Beam Line
[Vídeo Ciência Aberta](https://youtu.be/TS-3j783EJo)  
[Vídeo controle da luz](https://youtu.be/oZFGuXtiBgo)

### Software utilizado
#### [Anaconda 3](https://www.anaconda.com/distribution/)
#### Versão do pyhton (verificar)
```
python --version
```
#### Contagem regressiva do [Python 2](https://pythonclock.org/)


## Estatísticas:
<!--#### [Olhar Digital](https://olhardigital.com.br/noticia/as-10-linguagens-de-programacao-mais-populares-do-mundo-em-2018/74538)-->
#### [Dev Media](https://www.devmedia.com.br/top-10-linguagens-de-programacao-mais-usadas-no-mercado/39635)
#### [W Tricks](https://wtricks.com.br/linguagens-de-programacao-populares-2018/)
#### [PTI](https://www.profissionaisti.com.br/2019/01/7-linguagens-de-programacao-para-voce-aprender-em-2019/)
#### [WMC](https://medium.com/womakerscode/top-5-linguagens-para-2019-28df8aee7d10)


## Instalação de pacotes via [conda](https://anaconda.org/conda-forge/repo)
## Instalação de pacotes via [pip](https://pypi.org/)

## Princípios


#### A linguagem foi projetada com a filosofia de enfatizar a importância do esforço do programador sobre o esforço computacional.
#### Prioriza a legibilidade do código sobre a velocidade ou expressividade. 
#### Combina uma sintaxe concisa e clara com os recursos poderosos de sua biblioteca padrão e por módulos e frameworks desenvolvidos por terceiros.
#### Liguagem dinâmica de tipagem forte

In [4]:
# Exemplo variáveis
a = '1'
b = 2
print(a+str(b))

12


### Python é provavelmente a linguagem mais usada no mundo por não programadores

In [5]:
#The Zen of Python
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## Zen traduzido interpretação [livre](https://hacktoon.com/log/2015/programming-comics-3/)

# Sintaxe básica
# Não é preciso declarar variáveis
### Tipos de variáveis mais usadas
#### str = string
#### float = real
#### int = inteiro
#### complex = números complexos
#### bool = True or False
#### list = Lista mutáveis [algo, ] 
#### tuple = "lista" imutáveis (algo, )
#### set = conjuntos de elementos não repetidos  {algo, algo}
#### dict = dicionário chave valor {chave: valor, }

In [23]:
# Exemplo de list, dic, tuple, set
lista1 = [1, 2, 3, 4]
tupla = (2,4)
print(lista1)
lista2

[1, 2, 3, 4]


[2, 4]

In [20]:
lista1[2] = tupla
lista1

[1, 2, (2, 4), 4]

In [33]:
dici = {'Nome':'João',
        'Idade': 22,
        'Cidade': 'Teixeira Soares'}

## Saída

### print()

## Entrada

### input()

In [35]:
# Exemplo Saída
print('Olá mundo!')

Olá mundo!


In [37]:
var1 = 'joao'
idade = 22
print('Meu nome é:', var1, 'e tenho ', idade, 'anos')

Meu nome é:  joao e tenho  22 anos


In [38]:
print('Meu nome é: {} e tenho {} anos'.format(var1, idade))

Meu nome é: joao e tenho 22 anos


In [42]:
print(f'Meu nome é: {var1:10} e tenho {idade} anos')

Meu nome é: joao       e tenho 22 anos


In [50]:
# Exemplo entrada str, int, float
var2 = int(input('Digite um número: '))
var3 = int(input('Digite outro número: '))
print(var2 + var3)

Digite um número: 5
Digite outro número: 6
11


# Estruturas de controle

## Condicionais e estruturas de repetição
### if
### while
### for

## Operadores

### + Soma ou Concatenação
### - Subtração
### * Multiplicação
### / Divisão
### // Divisão de inteiros 
### ** Exponenciação
### % Módulo da divisão de inteiros (resto)
### = Atribuição, coloca o resultado da expressão a direita na identicação (variável) a esquerda
### == Comparação
### != Diferente

In [55]:
# Exemplo de condicional, pode ser ver se o número é maior ou menor
num = int(input('Digite um número: '))
if num > 10:
    print(f'O número {num} é maior que 10')
elif num == 10:
    print(f'O número {num} é igual a 10')
else:
    print(f'O número {num} não é maior que 10')

Digite um número: 10
O número 10 é igual a 10


In [60]:
# Exemplo de for com algum range()
palavra = 'loa_mundo'
for i in palavra:
    print(i)

o
l
a
_
m
u
n
d
o


In [61]:
lista1 = [1, 3, 5, 7, 9]
for joca in lista1:
    print(joca)


1
3
5
7
9


In [69]:
a = 0
while a == 0:
    a = int(input('digite a: '))
    print('ola')

digite a: 2
ola


In [ ]:
# # i++
# i = i +1 
# i += 1


In [68]:

# Exemplo de while com um True e esperando um número do usuário, var.isnumeric 

## Álgebra linear

## Curiosidades
### [Nome](https://youtu.be/Owxt5TUJKVA)
<!--### [Ponto e vírgula](https://scontent.fbfh3-1.fna.fbcdn.net/v/t1.0-9/49046413_749801262052982_2383082451229474816_n.jpg?_nc_cat=100&_nc_oc=AQk8dF19xQyxZTbALVxdTs72fJafnV-Te0Agu2zibsL3dUWKxrs31n40oexrI5ztBTk&_nc_ht=scontent.fbfh3-1.fna&oh=3b8cabbaabe965519ca710e005bd5ea7&oe=5D87C936)-->
### [C --> Python](https://scontent.fbfh3-2.fna.fbcdn.net/v/t1.0-9/61905486_2285562288373500_4149813872594780160_n.jpg?_nc_cat=108&_nc_oc=AQnRW_5uDGTkqRmwQBS6JM423GlhS7D0lLXKWSSXNtVFTsvdMKiLHFVfsuH9QyJhmpo&_nc_ht=scontent.fbfh3-2.fna&oh=b353abe1ab80e159461fdc8464861a8c&oe=5D9852F1)


In [72]:
import numpy as np 

In [76]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [79]:
help(np.cos)

Help on ufunc object:

cos = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [84]:
import numpy as np
import numpy.linalg as alg
from decimal import Decimal

In [89]:
a = Decimal(5/8.9)
a
b = str(a)
len(b)

55

In [97]:
V = np.array([4, 5, 6, 7])
V1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
V1.shape

(3, 3)

In [106]:
# Exemplo de matriz
A = np.array([[4,5,6],
              [10, 25, 89],
              [67, 9, 5]])

In [107]:
B = np.array([[4], 
              [5],
              [5]])

In [101]:
# A*B #
A@B #

array([[ 71],
       [610],
       [338]])

In [103]:
from numpy import array as mat

In [104]:
a =mat([[4,5,6],[7,8,9]])
a

array([[4, 5, 6],
       [7, 8, 9]])

In [109]:
alg?


# Usuários de MATLAB
[link](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html)

In [108]:
import numpy.linalg as alg
alg.solve(A, B)

array([[-0.06247479],
       [ 1.16777131],
       [-0.26482623]])

In [110]:
A.transpose()

array([[ 4, 10, 67],
       [ 5, 25,  9],
       [ 6, 89,  5]])

In [111]:
alg.inv(A)

array([[-0.03896029,  0.00167137,  0.0170019 ],
       [ 0.34078727, -0.02201602, -0.01705954],
       [-0.0913492 ,  0.01723244,  0.00288168]])

In [41]:
# função?

# Polinômios

In [114]:
p = np.poly1d([3,4,5])
print(p)

   2
3 x + 4 x + 5


In [123]:
m = p*p
# print(m)
var = 56

# print(p.integ(k=var))#k é a constante
# p = p.deriv()
print(p.deriv())

 
6 x + 4


In [146]:
a = np.linspace(0, 100, 10)
# a
# p(10)
print(a)
print(p(a))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[5.00000000e+00 4.19814815e+02 1.57537037e+03 3.47166667e+03
 6.10870370e+03 9.48648148e+03 1.36050000e+04 1.84642593e+04
 2.40642593e+04 3.04050000e+04]


In [147]:
novo = np.arange(0, 100, 0.9)
print(novo)
p(novo)


[ 0.   0.9  1.8  2.7  3.6  4.5  5.4  6.3  7.2  8.1  9.   9.9 10.8 11.7
 12.6 13.5 14.4 15.3 16.2 17.1 18.  18.9 19.8 20.7 21.6 22.5 23.4 24.3
 25.2 26.1 27.  27.9 28.8 29.7 30.6 31.5 32.4 33.3 34.2 35.1 36.  36.9
 37.8 38.7 39.6 40.5 41.4 42.3 43.2 44.1 45.  45.9 46.8 47.7 48.6 49.5
 50.4 51.3 52.2 53.1 54.  54.9 55.8 56.7 57.6 58.5 59.4 60.3 61.2 62.1
 63.  63.9 64.8 65.7 66.6 67.5 68.4 69.3 70.2 71.1 72.  72.9 73.8 74.7
 75.6 76.5 77.4 78.3 79.2 80.1 81.  81.9 82.8 83.7 84.6 85.5 86.4 87.3
 88.2 89.1 90.  90.9 91.8 92.7 93.6 94.5 95.4 96.3 97.2 98.1 99.  99.9]


array([5.000000e+00, 1.103000e+01, 2.192000e+01, 3.767000e+01,
       5.828000e+01, 8.375000e+01, 1.140800e+02, 1.492700e+02,
       1.893200e+02, 2.342300e+02, 2.840000e+02, 3.386300e+02,
       3.981200e+02, 4.624700e+02, 5.316800e+02, 6.057500e+02,
       6.846800e+02, 7.684700e+02, 8.571200e+02, 9.506300e+02,
       1.049000e+03, 1.152230e+03, 1.260320e+03, 1.373270e+03,
       1.491080e+03, 1.613750e+03, 1.741280e+03, 1.873670e+03,
       2.010920e+03, 2.153030e+03, 2.300000e+03, 2.451830e+03,
       2.608520e+03, 2.770070e+03, 2.936480e+03, 3.107750e+03,
       3.283880e+03, 3.464870e+03, 3.650720e+03, 3.841430e+03,
       4.037000e+03, 4.237430e+03, 4.442720e+03, 4.652870e+03,
       4.867880e+03, 5.087750e+03, 5.312480e+03, 5.542070e+03,
       5.776520e+03, 6.015830e+03, 6.260000e+03, 6.509030e+03,
       6.762920e+03, 7.021670e+03, 7.285280e+03, 7.553750e+03,
       7.827080e+03, 8.105270e+03, 8.388320e+03, 8.676230e+03,
       8.969000e+03, 9.266630e+03, 9.569120e+03, 9.8764

# ZEROS

In [149]:
import sympy as sp
x, y, z = sp.symbols('x y z')

In [150]:
f1 = x**2 + 2 * x + 4
f2 = x**2 + 2 * x*y + 4

In [151]:
sp.solveset(sp.Eq(f1, 0), x)

{-1 - sqrt(3)*I, -1 + sqrt(3)*I}

In [152]:
sp.solveset(sp.Eq(f2, f1), y)

{1}

In [153]:
sp.solveset(sp.Eq(f2, 0), z)

EmptySet()

In [ ]:
sp?

# Gráficos

In [154]:
import matplotlib.pyplot as plt
dir(plt)

['Annotation',
 'Arrow',
 'Artist',
 'AutoLocator',
 'Axes',
 'Button',
 'Circle',
 'Figure',
 'FigureCanvasBase',
 'FixedFormatter',
 'FixedLocator',
 'FormatStrFormatter',
 'Formatter',
 'FuncFormatter',
 'GridSpec',
 'IndexLocator',
 'Line2D',
 'LinearLocator',
 'Locator',
 'LogFormatter',
 'LogFormatterExponent',
 'LogFormatterMathtext',
 'LogLocator',
 'MaxNLocator',
 'MultipleLocator',
 'Normalize',
 'NullFormatter',
 'NullLocator',
 'Number',
 'PolarAxes',
 'Polygon',
 'Rectangle',
 'ScalarFormatter',
 'Slider',
 'Subplot',
 'SubplotTool',
 'Text',
 'TickHelper',
 'Widget',
 '_INSTALL_FIG_OBSERVER',
 '_IP_REGISTERED',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_auto_draw_if_interactive',
 '_backend_mod',
 '_get_running_interactive_framework',
 '_interactive_bk',
 '_log',
 '_pylab_helpers',
 '_setp',
 '_setup_pyplot_info_docstrings',
 '_show',
 'acorr',
 'angle_spectrum',
 'annotate',
 'arrow',
 'autoscale',

In [189]:
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 0.8, 0.9, 0.1, -0.8, -1.0])
z = np.polyfit(x, y, 5)
z

array([-8.33333333e-03,  1.25000000e-01, -5.75000000e-01,  6.25000000e-01,
        6.33333333e-01,  4.08176161e-15])

In [158]:
z[0]

-0.008333333333334084

In [190]:
fit= np.poly1d([z[0], z[1], z[2], z[3], z[4], z[5]])

In [184]:
print(fit)

         3          2
0.08704 x - 0.8135 x + 1.693 x - 0.03968


In [185]:
eixo = np.linspace(0, 5, 1000)
funcao = fit(eixo)
# funcao

In [186]:

titulo = 'Figura- f(x) = x$^{2}$'
plt.rcParams['figure.figsize'] = (11,7)
plt.title(titulo)
# plt.plot(x, y, 'g', marker='*')
plt.scatter(x, y, color='black', marker='*')
plt.plot(eixo, funcao, 'r')
# plt.savefig(titulo, format='svg')
plt.show()

In [179]:
%matplotlib qt
titulo = 'Figura- f(x) = x$^{2}$'
plt.rcParams['figure.figsize'] = (11,7)
plt.title(titulo)
# plt.plot(x, y, 'g', marker='*')
plt.scatter(x, y, color='black', marker='*')
plt.plot(eixo, funcao, 'r')
plt.savefig(titulo, format='svg')
plt.show()

/home/levandoski/anaconda3/lib/python3.7/site-packages/ipykernel/eventloops.py:106: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  app.exec_()
